### ISSUE TITLE
字体画布 em_size 为 1600，因此如果按照 12 像素渲染并不是 1:1，会造成模糊

### ISSUE THREAD

**Issue by TakWolf** [Luckeee/mplus_hzk_12#1]
RT，在 fontforge 里面对应这个设置：

菜单 -> Element -> Font Info -> General

![image](https://user-images.githubusercontent.com/6064962/91947037-04a08d80-ed32-11ea-9340-5447fa626693.png)

因为目前:
units_per_em = 1600
1 px = 100 units

所以只有按照 16 px 才是精确渲染
em_size 应该改为 1200
相应的，ascent、descent、underline 参数应该也要响应调整，以完美对应像素坐标

**Comment by py-zhao** [comment]
已修改 谢谢指教 我原来还不知道为啥有些模糊的
<img width="491" alt="截屏2020-12-19 05 04 16" src="https://user-images.githubusercontent.com/8073332/102672286-524ee200-41cb-11eb-9cf4-f8d239c3f8b2.png">
